*&---------------------------------------------------------------------*
*&  Include           YFI00005INTJPS_TOP
*&---------------------------------------------------------------------*

TABLES: pa0001, pa0002, pa0331, kna1, lfa1.

TYPE-POOLS: slis.
DATA: gs_layout TYPE slis_layout_alv,
      gs_fieldcat TYPE slis_t_fieldcat_alv.

TYPES: BEGIN OF tp_kna1,
         kunnr    TYPE kunnr,
         name1    TYPE name1_gp,
         sortl    TYPE sortl,
         stras    TYPE stras_gp,
         ort02    TYPE ort02_gp,
         pstlz    TYPE pstlz,
         mcod3    TYPE mcdd3,
         land1    TYPE land1_gp,
         regio    TYPE regio,
         telf1    TYPE telf1,
         stceg    TYPE stceg,
         stcd2    TYPE stcd2,
         katr1    TYPE katr1,
         katr2    TYPE katr2,
         katr3    TYPE katr3,
         katr4    TYPE katr4,
         katr5    TYPE katr5,
         katr6    TYPE katr6,
         katr7    TYPE katr7,
         katr8    TYPE katr8,
         katr9    TYPE katr9,
         katr10   TYPE katr10,
         zzbdate  TYPE gbdat,
         yfamint1 TYPE yfamint1,
         yfamint2 TYPE yfamint2,
         yfamint3 TYPE yfamint3,
         yfamint4 TYPE yfamint4,
         yfamint5 TYPE yfamint5,
         yfamint6 TYPE yfamint6,
         yfamint7 TYPE yfamint7,
         erro(1)  TYPE c,
       END OF tp_kna1,
       BEGIN OF tp_knb1,
         kunnr   TYPE kunnr,
         bukrs   TYPE bukrs,
         akont   TYPE akont,
         zuawa   TYPE dzuawa,
         fdgrv   TYPE fdgrv,
         pernr   TYPE pernr_d,
         zterm   TYPE dzterm,
         xzver   TYPE xzver,
         xverr   TYPE xverr_knb1,
         erro(1) TYPE c,
       END OF tp_knb1,
       BEGIN OF tp_knvv,
         kunnr   TYPE kunnr,
         vkorg   TYPE vkorg,
         vtweg   TYPE vtweg,
         spart   TYPE spart,
         bzirk   TYPE bzirk,
         vkbur   TYPE vkbur,
         vkgrp   TYPE vkgrp,
         kdgrp   TYPE kdgrp,
         ktgrd   TYPE ktgrd,
         waers   TYPE waers_v02d,
         kalks   TYPE kalks,
         versg   TYPE stgku,
         lprio   TYPE lprio,
         vsbed   TYPE vsbed,
         vwerk   TYPE dwerk_ext,
         prfre   TYPE prfre,
         inco1   TYPE inco1,
         inco2   TYPE inco2,
         zterm   TYPE dzterm,
         kvgr2   TYPE kvgr2,
         erro(1) TYPE c,
       END OF tp_knvv,
       BEGIN OF tp_lfa1,
         lifnr   TYPE lifnr,
         kunnr   TYPE kunnr,
         name1   TYPE name1_gp,
         sortl   TYPE sortl,
         stras   TYPE stras_gp,
         pstlz   TYPE pstlz,
         mcod3   TYPE mcdk3,
         land1   TYPE land1_gp,
         regio   TYPE regio,
         telf1   TYPE telf1,
         stceg   TYPE stceg,
         erro(1) TYPE c,
       END OF tp_lfa1,
       BEGIN OF tp_lfbk,
         lifnr   TYPE lifnr,
         banks   TYPE banks,
         bankl   TYPE bankk,
         bankn   TYPE bankn,
         bkont   TYPE bkont,
         erro(1) TYPE c,
       END OF tp_lfbk,
       BEGIN OF tp_lfb1,
         lifnr   TYPE lifnr,
         bukrs   TYPE bukrs,
         akont   TYPE akont,
         zuawa   TYPE dzuawa,
         fdgrv   TYPE fdgrv,
         pernr   TYPE pernr_d,
         zterm   TYPE dzterm,
         reprf   TYPE reprf,
         zwels   TYPE dzwels,
         erro(1) TYPE c,
       END OF tp_lfb1.

DATA: BEGIN OF gt_erro OCCURS 0,
        pernr LIKE pa0001-pernr,
        message(50) TYPE c,
      END OF gt_erro.

DATA: gt_kna1 TYPE TABLE OF tp_kna1 INITIAL SIZE 0,
      wa_kna1 TYPE tp_kna1,
      gt_knb1 TYPE TABLE OF tp_knb1 INITIAL SIZE 0,
      wa_knb1 TYPE tp_knb1,
      gt_knvv TYPE TABLE OF tp_knvv INITIAL SIZE 0,
      wa_knvv TYPE tp_knvv,
      gt_lfa1 TYPE TABLE OF tp_lfa1 INITIAL SIZE 0,
      wa_lfa1 TYPE tp_lfa1,
      gt_lfbk TYPE TABLE OF tp_lfbk INITIAL SIZE 0,
      wa_lfbk TYPE tp_lfbk,
      gt_lfb1 TYPE TABLE OF tp_lfb1 INITIAL SIZE 0,
      wa_lfb1 TYPE tp_lfb1,
*      gt_erro TYPE TABLE OF tp_erro INITIAL SIZE 0,
      wa_erro LIKE gt_erro.


DATA: gv_inactivo TYPE c.

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.
SELECT-OPTIONS s_pernr FOR pa0002-pernr OBLIGATORY.
SELECTION-SCREEN END OF BLOCK b1.
